"""
PDF Generator Service - Creates the interview prep guide PDF
"""
import os
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_LEFT


class PDFGenerator:
    def __init__(self):
        self.output_dir = os.path.join(os.path.dirname(__file__), "..", "..", "output")
        os.makedirs(self.output_dir, exist_ok=True)
        
        # Define styles
        self.styles = getSampleStyleSheet()
        self._create_custom_styles()
    
    def _create_custom_styles(self):
        """Create custom paragraph styles."""
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            alignment=TA_CENTER,
            textColor=HexColor('#0891b2')  # Cyan-600
        ))
        
        self.styles.add(ParagraphStyle(
            name='SectionTitle',
            parent=self.styles['Heading2'],
            fontSize=16,
            spaceBefore=20,
            spaceAfter=10,
            textColor=HexColor('#1e40af')  # Blue-800
        ))
        
        self.styles.add(ParagraphStyle(
            name='SubSection',
            parent=self.styles['Heading3'],
            fontSize=12,
            spaceBefore=15,
            spaceAfter=8,
            textColor=HexColor('#3b82f6')  # Blue-500
        ))
        
        self.styles.add(ParagraphStyle(
            name='CustomBodyText',
            parent=self.styles['Normal'],
            fontSize=10,
            spaceAfter=8,
            leading=14
        ))
    
    def generate_prep_guide(
        self,
        company_name: str,
        role_name: str,
        resume_analysis: dict,
        jd_analysis: dict,
        rounds: dict,
        strategy: dict,
        questions: dict,
        behavioral_questions: dict = None,
        technical_questions: dict = None
    ) -> str:
        """
        Generate a comprehensive interview prep guide PDF.
        
        Returns the path to the generated PDF.
        """
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"Interview_Prep_{company_name.replace(' ', '_')}_{timestamp}.pdf"
        filepath = os.path.join(self.output_dir, filename)
        
        doc = SimpleDocTemplate(
            filepath,
            pagesize=letter,
            rightMargin=0.75*inch,
            leftMargin=0.75*inch,
            topMargin=0.75*inch,
            bottomMargin=0.75*inch
        )
        
        story = []
        
        # Title Page
        story.append(Spacer(1, 2*inch))
        story.append(Paragraph(
            f"Interview Preparation Guide",
            self.styles['CustomTitle']
        ))
        story.append(Paragraph(
            f"{role_name} at {company_name}",
            self.styles['Heading2']
        ))
        story.append(Spacer(1, 0.5*inch))
        story.append(Paragraph(
            f"Generated by Candi AI | {datetime.now().strftime('%B %d, %Y')}",
            ParagraphStyle(name='SubTitle', parent=self.styles['Normal'], alignment=TA_CENTER, textColor=HexColor('#6b7280'))
        ))
        story.append(PageBreak())
        
        # Resume Analysis Section
        story.append(Paragraph("📄 Your Profile Analysis", self.styles['SectionTitle']))
        story.append(Paragraph(
            self._clean_markdown(resume_analysis.get('resume_analysis', 'Not available')),
            self.styles['CustomBodyText']
        ))
        story.append(Spacer(1, 0.3*inch))
        
        # JD Analysis Section
        story.append(Paragraph("📋 Job Requirements Analysis", self.styles['SectionTitle']))
        story.append(Paragraph(
            self._clean_markdown(jd_analysis.get('jd_analysis', 'Not available')),
            self.styles['CustomBodyText']
        ))
        story.append(PageBreak())
        
        # Interview Rounds
        story.append(Paragraph("🎯 Expected Interview Rounds", self.styles['SectionTitle']))
        story.append(Paragraph(
            self._clean_markdown(rounds.get('rounds_breakdown', 'Not available')),
            self.styles['CustomBodyText']
        ))
        story.append(Spacer(1, 0.3*inch))
        
        # Preparation Strategy
        story.append(Paragraph("📚 Your Preparation Strategy", self.styles['SectionTitle']))
        story.append(Paragraph(
            self._clean_markdown(strategy.get('preparation_strategy', 'Not available')),
            self.styles['CustomBodyText']
        ))
        story.append(PageBreak())
        
        # Questions & Answers
        story.append(Paragraph("❓ Practice Questions & Answers", self.styles['SectionTitle']))
        story.append(Paragraph(
            self._clean_markdown(questions.get('comprehensive_questions', 'Not available')),
            self.styles['CustomBodyText']
        ))
        
        if behavioral_questions:
            story.append(PageBreak())
            story.append(Paragraph("🤝 Behavioral Questions", self.styles['SectionTitle']))
            story.append(Paragraph(
                self._clean_markdown(behavioral_questions.get('behavioral_questions', 'Not available')),
                self.styles['CustomBodyText']
            ))
        
        if technical_questions:
            story.append(PageBreak())
            story.append(Paragraph("💻 Technical Deep Dives", self.styles['SectionTitle']))
            story.append(Paragraph(
                self._clean_markdown(technical_questions.get('technical_questions', 'Not available')),
                self.styles['CustomBodyText']
            ))
        
        # Build the PDF
        doc.build(story)
        
        return filepath
    
    def _clean_markdown(self, text: str) -> str:
        """
        Clean markdown formatting for PDF rendering.
        Convert **bold** to <b>bold</b>, etc.
        """
        if not text:
            return ""
        
        # Convert markdown bold to HTML
        import re
        text = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', text)
        text = re.sub(r'\*(.+?)\*', r'<i>\1</i>', text)
        
        # Convert markdown headers to bold
        text = re.sub(r'^### (.+)$', r'<b>\1</b>', text, flags=re.MULTILINE)
        text = re.sub(r'^## (.+)$', r'<b>\1</b>', text, flags=re.MULTILINE)
        text = re.sub(r'^# (.+)$', r'<b>\1</b>', text, flags=re.MULTILINE)
        
        # Convert bullet points
        text = re.sub(r'^- ', r'• ', text, flags=re.MULTILINE)
        text = re.sub(r'^\* ', r'• ', text, flags=re.MULTILINE)
        
        # Convert numbered lists
        text = re.sub(r'^(\d+)\. ', r'\1. ', text, flags=re.MULTILINE)
        
        # Replace newlines with <br/> for proper rendering
        text = text.replace('\n\n', '<br/><br/>')
        text = text.replace('\n', '<br/>')
        
        return text
